name: Build-All

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: fetch deps
      run: |
        sudo apt install gcc
        sudo apt install libc6-dev libglu1-mesa-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config
      
    - name: Build
      run: go build -o monsi
      
    - name: Upload Linux Build
      uses: actions/upload-artifact@v2
      with:
        name: monsi_linux
        path: ./monsi
  
  build-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -o monsi.exe
      
    - name: Upload Windows Build
      uses: actions/upload-artifact@v2
      with:
        name: monsi.exe
        path: ./monsi.exe
